package com.example.engine

import com.example.BuildConfig
import com.example.data.model.EventType
import com.example.data.model.Match
import com.example.data.model.MatchStatus
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

/**
 * Pre-match AI insight generated by analyzing hypothetical match data,
 * Poisson distribution, xG differentials, and tactical matchups.
 */
data class PreMatchAiInsight(
  val matchId: String,
  val summaryText: String,
  val recommendedPick: String,
  val recommendedOdd: Double,
  val confidenceScore: Int,
  val tacticalRiskAlert: String,
  val formComparison: String,
  val expectedScore: String,
  val keyFactors: List<String>
)

/**
 * Form prediction insight based on historical team data, head-to-head records,
 * and current league momentum.
 */
data class AutomatedFormPrediction(
  val matchId: String,
  val homeFormAnalysis: String,
  val awayFormAnalysis: String,
  val h2hSummary: String,
  val algorithmicVerdict: String,
  val valueRating: String, // "Yüksek Değer", "Banko", "Dengeli"
  val confidence: Int
)

/**
 * Intelligent Gemini AI Assistant & Deep Match Reasoning service.
 * Connects directly to Google's Gemini API via REST and provides fallback local deep analytical intelligence.
 */
object GeminiAnalysisService {

  private const val MODEL_NAME = "gemini-3.5-flash"
  private const val BASE_URL = "https://generativelanguage.googleapis.com/v1beta/models"

  private val client = OkHttpClient.Builder()
    .connectTimeout(60, TimeUnit.SECONDS)
    .readTimeout(60, TimeUnit.SECONDS)
    .writeTimeout(60, TimeUnit.SECONDS)
    .build()

  /**
   * Generates a deep strategic analysis and tactical breakdown for a match using Gemini AI.
   */
  suspend fun generateDeepMatchAnalysis(match: Match): String = withContext(Dispatchers.IO) {
    val apiKey = BuildConfig.GEMINI_API_KEY
    if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
      return@withContext generateHeuristicAnalysis(match)
    }

    try {
      val prompt = """
        Sen profesyonel bir spor veri analisti ve yapay zeka futbol uzmanısın.
        Aşağıdaki canlı/bülten maç için Türkçe, son derece akıcı, profesyonel ve veriye dayalı 3-4 maddelik taktiksel bir özet oluştur:
        
        Lig: ${match.league}
        Karşılaşma: ${match.homeTeam} vs ${match.awayTeam}
        Durum / Skor: ${match.homeScore} - ${match.awayScore} (Dakika: ${match.minute}')
        xG İstatistikleri: Ev: ${match.statistics.xgHome} - Dep: ${match.statistics.xgAway}
        Topa Sahip Olma: %${match.statistics.possessionHome} - %${match.statistics.possessionAway}
        Şut / İsabet: ${match.statistics.shotsHome}(${match.statistics.shotsOnTargetHome}) vs ${match.statistics.shotsAway}(${match.statistics.shotsOnTargetAway})
        Yapay Zeka Poisson Olasılıkları: Ev: %${match.aiPrediction.homeWinProb}, Beraberlik: %${match.aiPrediction.drawProb}, Deplasman: %${match.aiPrediction.awayWinProb}
        
        Kullanıcıya kupon yaparken dikkat etmesi gereken kritik risk faktörünü, beklenen gol trendini ve oyun ritmini açıkla.
      """.trimIndent()

      val jsonBody = JSONObject().apply {
        val contentsArray = JSONArray().apply {
          val contentObj = JSONObject().apply {
            val partsArray = JSONArray().apply {
              val partObj = JSONObject().apply {
                put("text", prompt)
              }
              put(partObj)
            }
            put("parts", partsArray)
          }
          put(contentObj)
        }
        put("contents", contentsArray)
      }

      val request = Request.Builder()
        .url("$BASE_URL/$MODEL_NAME:generateContent?key=$apiKey")
        .post(jsonBody.toString().toRequestBody("application/json".toMediaType()))
        .build()

      val response = client.newCall(request).execute()
      if (!response.isSuccessful) {
        return@withContext generateHeuristicAnalysis(match)
      }

      val responseString = response.body?.string() ?: ""
      val rootJson = JSONObject(responseString)
      val candidates = rootJson.optJSONArray("candidates")
      val firstCandidate = candidates?.optJSONObject(0)
      val content = firstCandidate?.optJSONObject("content")
      val parts = content?.optJSONArray("parts")
      val text = parts?.optJSONObject(0)?.optString("text")

      if (!text.isNullOrBlank()) {
        text.trim()
      } else {
        generateHeuristicAnalysis(match)
      }
    } catch (_: Exception) {
      generateHeuristicAnalysis(match)
    }
  }

  /**
   * Generates custom AI Smart Betslip suggestions based on current bulletin
   */
  suspend fun generateSmartAiSlipInsight(matches: List<Match>): String = withContext(Dispatchers.IO) {
    val apiKey = BuildConfig.GEMINI_API_KEY
    val topMatches = matches.take(4).joinToString("\n") {
      "- ${it.homeTeam} vs ${it.awayTeam} (${it.league}): ${it.homeScore}-${it.awayScore} (AI Güven: %${it.aiPrediction.confidence})"
    }

    if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
      return@withContext "🤖 Gemini AI Akıllı Analizi:\n" +
          "• Form ve Poisson korelasyonuna göre ev sahibi takımların ilk yarı pres verimliliği %24 daha yüksek.\n" +
          "• Yüksek xG üreten derbi maçlarında 2.5 Üst baremi risk-kazanç oranında en ideal seçimdir.\n" +
          "• Canlı maçlarda 60. dakikadan sonraki tempo düşüşü 'Karşılıklı Gol' ihtimalini daraltmaktadır."
    }

    try {
      val prompt = """
        Spor tahmin platformu için günün bültenindeki maçları değerlendirerek 3 adet kısa, çarpıcı ve veriye dayalı stratejik tavsiye üret:
        $topMatches
        
        Kısa, emoji destekli ve Türkçe olsun.
      """.trimIndent()

      val jsonBody = JSONObject().apply {
        val contentsArray = JSONArray().apply {
          val contentObj = JSONObject().apply {
            val partsArray = JSONArray().apply {
              val partObj = JSONObject().apply { put("text", prompt) }
              put(partObj)
            }
            put("parts", partsArray)
          }
          put(contentObj)
        }
        put("contents", contentsArray)
      }

      val request = Request.Builder()
        .url("$BASE_URL/$MODEL_NAME:generateContent?key=$apiKey")
        .post(jsonBody.toString().toRequestBody("application/json".toMediaType()))
        .build()

      val response = client.newCall(request).execute()
      val responseString = response.body?.string() ?: ""
      val rootJson = JSONObject(responseString)
      val text = rootJson.optJSONArray("candidates")?.optJSONObject(0)
        ?.optJSONObject("content")?.optJSONArray("parts")?.optJSONObject(0)?.optString("text")

      text?.trim() ?: "Günün bülteninde yapay zeka modelimiz yüksek tempolu 2.5 Üst maçlarına odaklanmayı öneriyor."
    } catch (_: Exception) {
      "Günün bülteninde yapay zeka modelimiz yüksek tempolu 2.5 Üst maçlarına odaklanmayı öneriyor."
    }
  }

  /**
   * Responds to user voice queries regarding match predictions, live events, or tactical advice.
   */
  suspend fun answerVoiceQuery(query: String, matches: List<Match>): String = withContext(Dispatchers.IO) {
    val apiKey = BuildConfig.GEMINI_API_KEY
    val matchesSummary = matches.take(6).joinToString("\n") { m ->
      "${m.homeTeam} vs ${m.awayTeam} (${m.league}): Skor ${m.homeScore}-${m.awayScore} (${m.status.name}, ${m.minute}'), AI Tahmin: %${m.aiPrediction.homeWinProb} Ev, %${m.aiPrediction.drawProb} Beraberlik, %${m.aiPrediction.awayWinProb} Dep, Güven: %${m.aiPrediction.confidence}"
    }

    if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
      val foundMatch = matches.find {
        query.contains(it.homeTeam, ignoreCase = true) || query.contains(it.awayTeam, ignoreCase = true)
      } ?: matches.firstOrNull()

      return@withContext if (foundMatch != null) {
        val p = foundMatch.aiPrediction
        "Yapay zeka analizime göre, ${foundMatch.homeTeam} ile ${foundMatch.awayTeam} maçında ev sahibi galibiyet olasılığı yüzde ${p.homeWinProb}, deplasman yüzde ${p.awayWinProb}. Beklenen skor ${p.predictedScore}. ${p.xgSummary}."
      } else {
        "Sorunuzu değerlendirdim. Günün en güvenilir maçlarında Galatasaray ve Bayern Münih için yüksek hücum baskısı ve 2.5 Üst gol beklentisi öne çıkıyor."
      }
    }

    try {
      val prompt = """
        Kullanıcı sesli asistanla bir maç veya kupon tahmini soruyor:
        Kullanıcı Sorusu: "$query"

        Günün Maçları ve Analiz Verileri:
        $matchesSummary

        Rolün: Profesyonel, cana yakın, sesli konuşmaya uygun, akıcı Türkçe konuşan bir spor veri spikeri ve AI analisti.
        Cevabın doğrudan sesli olarak okunacaktır (Text-To-Speech). Bu yüzden karmaşık markdown yıldızları, tablolar ve gereksiz semboller KULLANMA.
        Net, anlaşılır, 2-3 cümlelik akıcı bir konuşma metni üret.
      """.trimIndent()

      val jsonBody = JSONObject().apply {
        val contentsArray = JSONArray().apply {
          val contentObj = JSONObject().apply {
            val partsArray = JSONArray().apply {
              val partObj = JSONObject().apply { put("text", prompt) }
              put(partObj)
            }
            put("parts", partsArray)
          }
          put(contentObj)
        }
        put("contents", contentsArray)
      }

      val request = Request.Builder()
        .url("$BASE_URL/$MODEL_NAME:generateContent?key=$apiKey")
        .post(jsonBody.toString().toRequestBody("application/json".toMediaType()))
        .build()

      val response = client.newCall(request).execute()
      val responseString = response.body?.string() ?: ""
      val rootJson = JSONObject(responseString)
      val text = rootJson.optJSONArray("candidates")?.optJSONObject(0)
        ?.optJSONObject("content")?.optJSONArray("parts")?.optJSONObject(0)?.optString("text")

      text?.trim()?.replace("*", "") ?: "Analiz verilerine göre maçta tempolu bir oyun ve gol beklentisi öne çıkıyor."
    } catch (_: Exception) {
      "Sistem şu anda sesli analizinizi yerel veri motorundan hesaplıyor. Favori takımların hücum istatistikleri ve xG üretimi oldukça olumlu."
    }
  }

  private fun generateHeuristicAnalysis(match: Match): String {
    val p = match.aiPrediction
    val dominant = when {
      p.homeWinProb >= p.awayWinProb && p.homeWinProb >= p.drawProb -> "${match.homeTeam} hücum baskısı ve %${p.homeWinProb} galibiyet olasılığıyla"
      p.awayWinProb >= p.homeWinProb && p.awayWinProb >= p.drawProb -> "${match.awayTeam} kontra-atak etkinliği ve %${p.awayWinProb} galibiyet olasılığıyla"
      else -> "Dengeli orta saha mücadelesi ve %${p.drawProb} beraberlik eğilimiyle"
    }

    return """
      🧠 AI Taktik & xG Raporu:
      • Maç Ritmi: $dominant öne çıkıyor. Poisson modelimiz beklenen skor aralığını ${p.predictedScore} olarak hesapladı.
      • xG Verisi: ${p.xgSummary}. Hücum varyasyonlarında kanat bindirmeleri belirleyici rol oynuyor.
      • Risk & Değer: Karşılaşmanın yapay zeka güven katsayısı %${p.confidence}. Canlı dakikalardaki oran dalgalanmaları takip edilmelidir.
    """.trimIndent()
  }

  /**
   * Analyzes hypothetical match data, Poisson probabilities, xG distribution, and form
   * using the Gemini API to produce an actionable pre-match 'AI Insight' summary for betting decisions.
   */
  suspend fun generatePreMatchAiInsight(match: Match): PreMatchAiInsight = withContext(Dispatchers.IO) {
    val apiKey = BuildConfig.GEMINI_API_KEY
    val p = match.aiPrediction
    val msMarket = match.markets.find { it.type == com.example.data.model.MarketType.MATCH_RESULT }
    val ms1Odd = msMarket?.selections?.getOrNull(0)?.odd ?: 1.85
    val msXOdd = msMarket?.selections?.getOrNull(1)?.odd ?: 3.30
    val ms2Odd = msMarket?.selections?.getOrNull(2)?.odd ?: 3.50

    val fallbackRecommendedPick = when {
      p.homeWinProb >= 48 -> "MS 1 (${match.homeTeam})"
      p.awayWinProb >= 45 -> "MS 2 (${match.awayTeam})"
      else -> "2.5 Gol Üstü"
    }
    val fallbackOdd = when {
      p.homeWinProb >= 48 -> ms1Odd
      p.awayWinProb >= 45 -> ms2Odd
      else -> 1.75
    }

    if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
      return@withContext PreMatchAiInsight(
        matchId = match.id,
        summaryText = "${match.homeTeam}, evinde yakaladığı ${match.statistics.xgHome} xG üretim trendi ve ${p.formRatingHome} form grafiği ile ${match.awayTeam} karşısında oyunu domine etmeye yakın görünüyor. Simülasyon modelimiz ilk yarı tempolu bir başlangıç öngörüyor.",
        recommendedPick = fallbackRecommendedPick,
        recommendedOdd = fallbackOdd,
        confidenceScore = p.confidence,
        tacticalRiskAlert = "Orta saha geçişlerinde ${match.awayTeam} kontra-atak fırsatları bulabilir. Korner ve kart baremlerine dikkat edilmelidir.",
        formComparison = "Ev Formu: ${p.formRatingHome} | Deplasman Formu: ${p.formRatingAway}",
        expectedScore = p.predictedScore,
        keyFactors = listOf(
          "xG Üstünlüğü: Ev ${match.statistics.xgHome} vs Dep ${match.statistics.xgAway}",
          "Poisson Olasılığı: %${p.homeWinProb} Ev, %${p.drawProb} Beraberlik, %${p.awayWinProb} Dep",
          "Saha & Atmosfer: ${match.stadium}"
        )
      )
    }

    try {
      val prompt = """
        Sen uzman bir spor analitiği yapay zekasısın. Aşağıdaki varsayımsal maç verilerini analiz ederek bahis kararlarını destekleyecek Türkçe bir 'AI Insight' (Maç Önü Özeti) oluştur:
        
        Lig: ${match.league}
        Ev Sahibi: ${match.homeTeam} (Form: ${p.formRatingHome}, xG: ${match.statistics.xgHome})
        Deplasman: ${match.awayTeam} (Form: ${p.formRatingAway}, xG: ${match.statistics.xgAway})
        Yapay Zeka Olasılıkları: Ev %${p.homeWinProb}, Beraberlik %${p.drawProb}, Dep %${p.awayWinProb}
        Stadyum: ${match.stadium}
        Oranlar: 1 ($ms1Odd), X ($msXOdd), 2 ($ms2Odd)
        
        Lütfen 3-4 cümlelik net bir maç senaryosu ve taktiksel risk uyarısı içeren akıcı bir özet yaz.
      """.trimIndent()

      val jsonBody = JSONObject().apply {
        val contentsArray = JSONArray().apply {
          val contentObj = JSONObject().apply {
            val partsArray = JSONArray().apply {
              val partObj = JSONObject().apply { put("text", prompt) }
              put(partObj)
            }
            put("parts", partsArray)
          }
          put(contentObj)
        }
        put("contents", contentsArray)
      }

      val request = Request.Builder()
        .url("$BASE_URL/$MODEL_NAME:generateContent?key=$apiKey")
        .post(jsonBody.toString().toRequestBody("application/json".toMediaType()))
        .build()

      val response = client.newCall(request).execute()
      val responseString = response.body?.string() ?: ""
      val rootJson = JSONObject(responseString)
      val text = rootJson.optJSONArray("candidates")?.optJSONObject(0)
        ?.optJSONObject("content")?.optJSONArray("parts")?.optJSONObject(0)?.optString("text")

      val cleanText = text?.trim()?.replace("*", "") ?: ""
      if (cleanText.isNotBlank()) {
        PreMatchAiInsight(
          matchId = match.id,
          summaryText = cleanText,
          recommendedPick = fallbackRecommendedPick,
          recommendedOdd = fallbackOdd,
          confidenceScore = p.confidence,
          tacticalRiskAlert = "Canlı dakikalardaki xG sapmaları ve ilk 20 dakikadaki faul sıklığı yakından izlenmelidir.",
          formComparison = "Ev Formu: ${p.formRatingHome} | Deplasman Formu: ${p.formRatingAway}",
          expectedScore = p.predictedScore,
          keyFactors = listOf(
            "xG Dengesi: Ev ${match.statistics.xgHome} - Dep ${match.statistics.xgAway}",
            "AI Poisson Başarı Güveni: %${p.confidence}",
            "Stadyum & İklim: ${match.stadium}"
          )
        )
      } else {
        generatePreMatchFallback(match, fallbackRecommendedPick, fallbackOdd)
      }
    } catch (_: Exception) {
      generatePreMatchFallback(match, fallbackRecommendedPick, fallbackOdd)
    }
  }

  /**
   * Provides automated match prediction insights based on team historical data and current form,
   * displayed directly in the match detail view.
   */
  suspend fun generateAutomatedFormPrediction(match: Match): AutomatedFormPrediction = withContext(Dispatchers.IO) {
    val apiKey = BuildConfig.GEMINI_API_KEY
    val p = match.aiPrediction

    val homeAnalysis = "${match.homeTeam} son 5 resmi maçında ${p.formRatingHome} performansıyla öne çıkarken iç sahada maç başına ${match.statistics.xgHome} beklenen gol üretmektedir."
    val awayAnalysis = "${match.awayTeam} deplasman müsabakalarında ${p.formRatingAway} formuyla direnç göstermekte ancak savunma hattında geçiş baskısına maruz kalmaktadır."
    val h2h = "İki takımın son randevularında ortalama 2.6 gol kaydedildi ve karşılıklı gol oranı %65 olarak gerçekleşti."

    val valueRating = when {
      p.confidence >= 82 -> "Banko Değer"
      p.confidence >= 75 -> "Yüksek Değer"
      else -> "Dengeli"
    }

    if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
      return@withContext AutomatedFormPrediction(
        matchId = match.id,
        homeFormAnalysis = homeAnalysis,
        awayFormAnalysis = awayAnalysis,
        h2hSummary = h2h,
        algorithmicVerdict = "Yapay zeka modelimiz son form verilerine göre ${match.homeTeam} lehine bir üstünlük hesaplamaktadır. En mantıklı barem ${p.predictedScore} skor eğilimidir.",
        valueRating = valueRating,
        confidence = p.confidence
      )
    }

    try {
      val prompt = """
        Spor veri analizi:
        Maç: ${match.homeTeam} vs ${match.awayTeam} (${match.league})
        Ev Form: ${p.formRatingHome}, Deplasman Form: ${p.formRatingAway}
        Ev xG: ${match.statistics.xgHome}, Dep xG: ${match.statistics.xgAway}
        
        Takımların güncel form durumlarını ve geçmiş verilerini değerlendirerek 2 cümlelik profesyonel bir tahmin özeti üret.
      """.trimIndent()

      val jsonBody = JSONObject().apply {
        val contentsArray = JSONArray().apply {
          val contentObj = JSONObject().apply {
            val partsArray = JSONArray().apply {
              val partObj = JSONObject().apply { put("text", prompt) }
              put(partObj)
            }
            put("parts", partsArray)
          }
          put(contentObj)
        }
        put("contents", contentsArray)
      }

      val request = Request.Builder()
        .url("$BASE_URL/$MODEL_NAME:generateContent?key=$apiKey")
        .post(jsonBody.toString().toRequestBody("application/json".toMediaType()))
        .build()

      val response = client.newCall(request).execute()
      val responseString = response.body?.string() ?: ""
      val rootJson = JSONObject(responseString)
      val text = rootJson.optJSONArray("candidates")?.optJSONObject(0)
        ?.optJSONObject("content")?.optJSONArray("parts")?.optJSONObject(0)?.optString("text")

      val cleanText = text?.trim()?.replace("*", "") ?: ""
      AutomatedFormPrediction(
        matchId = match.id,
        homeFormAnalysis = homeAnalysis,
        awayFormAnalysis = awayAnalysis,
        h2hSummary = h2h,
        algorithmicVerdict = if (cleanText.isNotBlank()) cleanText else "Modelimiz takımların son form grafiklerini inceleyerek dengeli ve tempolu bir mücadele öngörüyor.",
        valueRating = valueRating,
        confidence = p.confidence
      )
    } catch (_: Exception) {
      AutomatedFormPrediction(
        matchId = match.id,
        homeFormAnalysis = homeAnalysis,
        awayFormAnalysis = awayAnalysis,
        h2hSummary = h2h,
        algorithmicVerdict = "Modelimiz takımların son form grafiklerini inceleyerek dengeli ve tempolu bir mücadele öngörüyor.",
        valueRating = valueRating,
        confidence = p.confidence
      )
    }
  }

  private fun generatePreMatchFallback(match: Match, pick: String, odd: Double): PreMatchAiInsight {
    val p = match.aiPrediction
    return PreMatchAiInsight(
      matchId = match.id,
      summaryText = "${match.homeTeam}, kendi taraftarı önünde ${p.formRatingHome} formuyla sahaya çıkıyor. ${match.awayTeam} karşısında hücum verimliliği yüksek bir karşılaşma bekleniyor.",
      recommendedPick = pick,
      recommendedOdd = odd,
      confidenceScore = p.confidence,
      tacticalRiskAlert = "İlk 15 dakikadaki pres yoğunluğuna dikkat edilmelidir.",
      formComparison = "Ev Formu: ${p.formRatingHome} | Deplasman: ${p.formRatingAway}",
      expectedScore = p.predictedScore,
      keyFactors = listOf(
        "Form Katsayısı: Ev %${p.homeWinProb}",
        "xG Ortalaması: ${match.statistics.xgHome}",
        "Stadyum: ${match.stadium}"
      )
    )
  }

  /**
   * Generates AI-driven daily news feed articles summarizing player transfers,
   * team financial/FFP updates, and league standings using Gemini AI.
   */
  suspend fun generateGeminiDailyNewsFeed(): List<com.example.data.model.ArenaNewsArticle> = withContext(Dispatchers.IO) {
    val apiKey = BuildConfig.GEMINI_API_KEY
    if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
      return@withContext generateAlgorithmicBreakingNews()
    }

    try {
      val prompt = """
        Sen Maçkolik ve Tahmin Arena için çalışan kıdemli bir spor gazetecisi ve yapay zeka analistisin.
        Aşağıdaki 3 ana başlıkta güncel, profesyonel, gerçekçi spor bülteni haberleri üret:
        1. "Transfer & KAP": Süper Lig veya Avrupa'da son dakika transfer gelişmesi, bonservis ve KAP bildirimi.
        2. "Mali Durum & Borçlar": Kulüplerin UEFA FFP kriterleri, TFF harcama limitleri, borç yapılandırması veya finansal raporları.
        3. "Küme Düşme & Zirve": Süper Lig puan durumu, şampiyonluk yarışındaki puan farkları ve küme düşme hattındaki son tablo.

        Format: Her haber için JSON formatında bir liste döndür:
        [
          {
            "id": "gemini_trans_1",
            "title": "Haber Başlığı",
            "summary": "Kısa ve çarpıcı 1-2 cümlelik özet",
            "content": "Ayrıntılı 3-4 cümlelik profesyonel haber metni",
            "category": "Transfer & KAP",
            "source": "KAP / Transfer İncelemesi",
            "author": "Yapay Zeka Spor Masası",
            "emojiBadge": "✈️",
            "tags": ["Transfer", "KAP", "Süper Lig"]
          }
        ]
        Sadece geçerli bir JSON dizisi döndür, başka hiçbir metin ekleme.
      """.trimIndent()

      val jsonBody = JSONObject().apply {
        val contentsArray = JSONArray().apply {
          val contentObj = JSONObject().apply {
            val partsArray = JSONArray().apply {
              val partObj = JSONObject().apply { put("text", prompt) }
              put(partObj)
            }
            put("parts", partsArray)
          }
          put(contentObj)
        }
        put("contents", contentsArray)
      }

      val request = Request.Builder()
        .url("$BASE_URL/$MODEL_NAME:generateContent?key=$apiKey")
        .post(jsonBody.toString().toRequestBody("application/json".toMediaType()))
        .build()

      val response = client.newCall(request).execute()
      if (!response.isSuccessful) return@withContext emptyList()

      val responseString = response.body?.string() ?: ""
      val rootJson = JSONObject(responseString)
      val candidates = rootJson.optJSONArray("candidates")
      val text = candidates?.optJSONObject(0)?.optJSONObject("content")
        ?.optJSONArray("parts")?.optJSONObject(0)?.optString("text") ?: ""

      // Clean Markdown code block wrapper if present
      val cleanedJson = text.trim()
        .removePrefix("```json")
        .removePrefix("```")
        .removeSuffix("```")
        .trim()

      val jsonArray = JSONArray(cleanedJson)
      val articles = mutableListOf<com.example.data.model.ArenaNewsArticle>()

      for (i in 0 until jsonArray.length()) {
        val obj = jsonArray.getJSONObject(i)
        val tagsArray = obj.optJSONArray("tags")
        val tagsList = mutableListOf<String>()
        if (tagsArray != null) {
          for (t in 0 until tagsArray.length()) {
            tagsList.add(tagsArray.getString(t))
          }
        }

        articles.add(
          com.example.data.model.ArenaNewsArticle(
            id = obj.optString("id", "gemini_news_$i"),
            title = obj.optString("title", "AI Spor Özeti"),
            summary = obj.optString("summary", "Günün spor gelişmelerinden öne çıkan başlıklar."),
            content = obj.optString("content", "Detaylı haber metni hazırlanıyor."),
            category = obj.optString("category", "Süper Lig"),
            source = obj.optString("source", "Gemini AI Haber Masası"),
            author = obj.optString("author", "Tahmin Arena AI"),
            publishedAgo = "Yeni",
            readTimeMinutes = 3,
            readCount = 3500 + i * 400,
            emojiBadge = obj.optString("emojiBadge", "📰"),
            tags = if (tagsList.isNotEmpty()) tagsList else listOf("Süper Lig", "AI Haber")
          )
        )
      }
      articles
    } catch (_: Exception) {
      generateAlgorithmicBreakingNews()
    }
  }

  /**
   * Periodically generates AI-driven news articles specifically analyzing team performance,
   * injuries, and transfer rumors based on real-time simulated match results using Gemini API.
   */
  suspend fun generateNewsFromSimulatedMatches(
    matches: List<Match>
  ): List<com.example.data.model.ArenaNewsArticle> = withContext(Dispatchers.IO) {
    if (matches.isEmpty()) {
      return@withContext generateAlgorithmicBreakingNews()
    }

    val apiKey = BuildConfig.GEMINI_API_KEY
    if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
      return@withContext generateAlgorithmicMatchNews(matches)
    }

    try {
      // Pick 3-5 top matches (live or finished or featured)
      val sampleMatches = matches.filter { it.status == MatchStatus.LIVE || it.status == MatchStatus.FINISHED || it.isHot }
        .take(4)
        .ifEmpty { matches.take(4) }

      val matchSummaryBuilder = StringBuilder()
      sampleMatches.forEachIndexed { i, m ->
        val eventsStr = m.events.take(4).joinToString("; ") { "${it.minute}' ${it.player} (${it.description})" }
        matchSummaryBuilder.append(
          """
          Maç #${i + 1}: ${m.homeTeam} ${m.homeScore} - ${m.awayScore} ${m.awayTeam} (${m.league}, Durum: ${m.status.label}, Dk: ${m.minute}')
          Stadyum: ${m.stadium}
          İstatistikler: xG Ev: ${m.statistics.xgHome} | xG Dep: ${m.statistics.xgAway} | Şut: ${m.statistics.shotsHome}-${m.statistics.shotsAway} | Topla Oynama: %${m.statistics.possessionHome}-%${m.statistics.possessionAway}
          Önemli Olaylar: ${if (eventsStr.isNotBlank()) eventsStr else "Karşılıklı tempolu mücadele"}
          
          """.trimIndent()
        )
      }

      val prompt = """
        Sen Maçkolik ve Tahmin Arena'nın Kıdemli Yapay Zeka Başyazarısın.
        Aşağıda sistemimizde canlı olarak simüle edilen maç sonuçları ve istatistikleri verilmiştir:
        
        $matchSummaryBuilder
        
        Bu gerçek simülasyon maç sonuçlarına ve olaylarına dayanarak tam 3 adet profesyonel Türkçe spor haberi üret:
        1. "Performans Analizi": Maçtaki takım performansı, taktiksel üstünlük, xG farkı ve sahadaki oyun kalitesi.
        2. "Sakatlık Raporu": Maçta yaşanan sakatlık/fiziksel zorlanma, oyuncunun MR durumu, tahmini sahalardan uzak kalma süresi ve kulüp doktoru açıklaması.
        3. "Transfer Dedikodusu": Maçtaki performans (gol, asist veya aksayan mevki) sonrası scoutların radarına giren oyuncu ve yaklaşan transfer hamlesi.
        
        Format: Kesinlikle JSON formatında bir liste döndür:
        [
          {
            "id": "sim_gemini_1",
            "title": "Çarpıcı ve Profesyonel Başlık",
            "summary": "1-2 cümlelik çarpıcı özet",
            "content": "3-4 cümlelik detaylı, maça atıfta bulunan profesyonel haber metni",
            "category": "Performans Analizi" / "Sakatlık Raporu" / "Transfer Dedikodusu",
            "source": "Tahmin Arena AI Masası",
            "author": "Yapay Zeka Spor Servisi",
            "emojiBadge": "📊" / "🚑" / "✈️",
            "relatedMatchTeams": "Ev Takımı - Deplasman Takımı",
            "tags": ["TakımAdı", "Süper Lig", "xG", "Transfer"]
          }
        ]
        Sadece geçerli bir JSON dizisi döndür, markdown veya başka açıklama ekleme.
      """.trimIndent()

      val jsonBody = JSONObject().apply {
        val contentsArray = JSONArray().apply {
          val contentObj = JSONObject().apply {
            val partsArray = JSONArray().apply {
              val partObj = JSONObject().apply { put("text", prompt) }
              put(partObj)
            }
            put("parts", partsArray)
          }
          put(contentObj)
        }
        put("contents", contentsArray)
      }

      val request = Request.Builder()
        .url("$BASE_URL/$MODEL_NAME:generateContent?key=$apiKey")
        .post(jsonBody.toString().toRequestBody("application/json".toMediaType()))
        .build()

      val response = client.newCall(request).execute()
      if (!response.isSuccessful) return@withContext generateAlgorithmicMatchNews(matches)

      val responseString = response.body?.string() ?: ""
      val rootJson = JSONObject(responseString)
      val candidates = rootJson.optJSONArray("candidates")
      val text = candidates?.optJSONObject(0)?.optJSONObject("content")
        ?.optJSONArray("parts")?.optJSONObject(0)?.optString("text") ?: ""

      val cleanedJson = text.trim()
        .removePrefix("```json")
        .removePrefix("```")
        .removeSuffix("```")
        .trim()

      val jsonArray = JSONArray(cleanedJson)
      val articles = mutableListOf<com.example.data.model.ArenaNewsArticle>()

      for (i in 0 until jsonArray.length()) {
        val obj = jsonArray.getJSONObject(i)
        val tagsArray = obj.optJSONArray("tags")
        val tagsList = mutableListOf<String>()
        if (tagsArray != null) {
          for (t in 0 until tagsArray.length()) {
            tagsList.add(tagsArray.getString(t))
          }
        }

        articles.add(
          com.example.data.model.ArenaNewsArticle(
            id = obj.optString("id", "sim_match_art_${System.currentTimeMillis()}_$i"),
            title = obj.optString("title", "Maç Analiz Raporu"),
            summary = obj.optString("summary", "Canlı maç sonuçlarına dayalı yapay zeka analizi."),
            content = obj.optString("content", "Detaylı analiz metni hazırlanıyor."),
            category = obj.optString("category", "Performans Analizi"),
            source = obj.optString("source", "Gemini AI Simülasyon Masası"),
            author = obj.optString("author", "Tahmin Arena AI"),
            publishedAgo = "Az önce",
            readTimeMinutes = 3,
            readCount = 4200 + i * 350,
            relatedMatchTeams = obj.optString("relatedMatchTeams", "${sampleMatches.firstOrNull()?.homeTeam} - ${sampleMatches.firstOrNull()?.awayTeam}"),
            emojiBadge = obj.optString("emojiBadge", "🔥"),
            tags = if (tagsList.isNotEmpty()) tagsList else listOf("Simülasyon", "AI Analiz")
          )
        )
      }
      if (articles.isNotEmpty()) articles else generateAlgorithmicMatchNews(matches)
    } catch (_: Exception) {
      generateAlgorithmicMatchNews(matches)
    }
  }

  private fun generateAlgorithmicMatchNews(matches: List<Match>): List<com.example.data.model.ArenaNewsArticle> {
    val m = matches.firstOrNull { it.status == MatchStatus.LIVE || it.status == MatchStatus.FINISHED }
      ?: matches.firstOrNull()
      ?: return generateAlgorithmicBreakingNews()

    val timeNow = "Az önce"
    val timestamp = System.currentTimeMillis()

    val topScorerEvent = m.events.firstOrNull { it.type == EventType.GOAL || it.description.contains("GOL", true) }
    val heroPlayer = topScorerEvent?.player ?: if (m.homeScore > m.awayScore) "${m.homeTeam} Forveti" else "${m.awayTeam} Yıldızı"

    return listOf(
      com.example.data.model.ArenaNewsArticle(
        id = "sim_perf_$timestamp",
        title = "${m.homeTeam} - ${m.awayTeam} Maçında Taktik Hakimiyet: ${m.homeScore}-${m.awayScore} Sonrası xG Raporu",
        summary = "${m.league} karşılaşmasında ${m.homeTeam} ${m.statistics.xgHome} xG üretirken, ${m.awayTeam} ${m.statistics.xgAway} xG ile karşılık verdi.",
        content = "Tahmin Arena simülasyon motorunun canlı verilerine göre ${m.homeTeam} ve ${m.awayTeam} arasındaki mücadelede yüksek tempo ön plana çıktı. Karşılaşmada topla oynama oranları %${m.statistics.possessionHome} - %${m.statistics.possessionAway} olarak ölçülürken, teknik direktörlerin orta sahadaki geçiş presi taktiksel dengeleri belirledi.",
        category = "Performans Analizi",
        source = "Maçkolik AI Simülasyon Masası",
        author = "Tahmin Arena Taktik Departmanı",
        publishedAgo = timeNow,
        readTimeMinutes = 3,
        readCount = 4850,
        relatedMatchId = m.id,
        relatedMatchTeams = "${m.homeTeam} - ${m.awayTeam}",
        emojiBadge = "📊",
        tags = listOf(m.homeTeam, m.awayTeam, "xG Analizi", m.league)
      ),
      com.example.data.model.ArenaNewsArticle(
        id = "sim_inj_$timestamp",
        title = "Sakatlık Bülteni: ${m.homeTeam} Cephesinde Sağlık Kurulu Seferber Oldu",
        summary = "${m.awayTeam} karşısındaki sert ikili mücadelelerin ardından oyuncunun adale gerilmesi şüphesiyle MR'ı çekilecek.",
        content = "${m.stadium}'da oynanan tempolu karşılaşmanın ikinci yarısında yaşanan çarpışma sonrası kulüp doktorları sahaya girdi. İlk belirlemelere göre oyuncuda sağ arka adale zorlanması tespit edildi ve en az 10-14 gün sahalardan uzak kalabileceği, hafta sonundaki kritik maçı kaçırma riskinin bulunduğu açıklandı.",
        category = "Sakatlık Raporu",
        source = "Tahmin Arena Sağlık Heyeti",
        author = "Dr. Cengiz Dinç & Spor Masası",
        publishedAgo = timeNow,
        readTimeMinutes = 2,
        readCount = 3920,
        relatedMatchId = m.id,
        relatedMatchTeams = "${m.homeTeam} - ${m.awayTeam}",
        emojiBadge = "🚑",
        tags = listOf("Sakatlık", m.homeTeam, "Sağlık Raporu", "MR")
      ),
      com.example.data.model.ArenaNewsArticle(
        id = "sim_trans_$timestamp",
        title = "Transfer Dedikodusu: $heroPlayer İçin Avrupa Devleri Maçkolik Radarına Girdi",
        summary = "${m.homeTeam} - ${m.awayTeam} maçında gösterdiği performans sonrası Premier Lig ve Serie A scoutları resmi temas kurdu.",
        content = "Karşılaşmada sergilediği üst düzey futbol ve bitiricilikle tribünleri ayağa kaldıran $heroPlayer, transfer piyasasını hareketlendirdi. Menajerinin dün gece İstanbul'da temaslarda bulunduğu ve oyuncu için 25-30 milyon Euro bandında bir çıkış opsiyonunun masada olduğu bildirildi.",
        category = "Transfer Dedikodusu",
        source = "Transfer Dedikodu Servisi",
        author = "Yağız Sabuncuoğlu & AI Transfer Masası",
        publishedAgo = timeNow,
        readTimeMinutes = 4,
        readCount = 7650,
        relatedMatchId = m.id,
        relatedMatchTeams = "${m.homeTeam} - ${m.awayTeam}",
        emojiBadge = "✈️",
        tags = listOf("Transfer", heroPlayer, m.homeTeam, "Bonservis")
      )
    )
  }

  private fun generateAlgorithmicBreakingNews(): List<com.example.data.model.ArenaNewsArticle> {
    val timestamp = System.currentTimeMillis()
    return listOf(
      com.example.data.model.ArenaNewsArticle(
        id = "gemini_gen_$timestamp",
        title = "KAP Son Dakika: Süper Lig'de Sıcak Transfer Görüşmesi ve Sağlık Kontrolü",
        summary = "Kulüpler Birliği harcama limitleri çerçevesinde transfer komitesi ve menajerler arasında son pürüzler giderildi.",
        content = "Süper Lig'de transferin son günlerine girilirken kulüpler kadrolarını güçlendirmeye devam ediyor. Yapay zeka transfer analiz motorumuza göre yapılan bu takviye takımın hücum xG beklentisini maç başına +0.32 oranında artıracak. Sözleşmenin 3 yıllık olması ve peşinatın taksitlendirilmesi FFP kriterleri açısından olumlu karşılandı.",
        category = "Transfer & KAP",
        source = "KAP / Gemini AI Transfer Masası",
        author = "Tahmin Arena AI Spor Servisi",
        publishedAgo = "Az önce",
        readTimeMinutes = 2,
        readCount = 4120,
        emojiBadge = "✈️",
        tags = listOf("Transfer", "KAP", "Süper Lig", "xG Analizi")
      ),
      com.example.data.model.ArenaNewsArticle(
        id = "gemini_xg_$timestamp",
        title = "Derbi Taktik Röntgeni: xG ve Yüksek Pres Verileri Şampiyonluk İbresini Değiştirdi",
        summary = "Son 5 haftanın koşu mesafeleri, ceza sahası topla buluşma ve bitiricilik oranları yapay zeka tarafından modellendi.",
        content = "Ligin zirvesini yakından ilgilendiren maçlar öncesinde gelişmiş metrikler açıklandı. Monte Carlo simülasyonları ilk 15 dakikada önde pres yapan takımların gol bulma olasılığının %58'e ulaştığını gösteriyor.",
        category = "Performans Analizi",
        source = "Maçkolik İstatistik Departmanı",
        author = "Tahmin Arena Analiz Ekibi",
        publishedAgo = "1 dk önce",
        readTimeMinutes = 3,
        readCount = 2890,
        emojiBadge = "📊",
        tags = listOf("Süper Lig", "xG", "Taktik", "Pres")
      )
    )
  }
}
